#######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options: 
# https://jupyterbook.org/customize/config.html

#######################################################################################
# Book settings
title                       : "Adding Phase Analysis to SST"  # The title of the book. Will be placed in the left navbar.
author                      : Patrick Lavin  # The author of the book
copyright                   : "2020"  # Copyright year to be placed in the footer
logo                        : logo.png  # A path to the book logo
repository:
  url: https://github.com/plavin/comp_arch_book
html:
  use_repository_button: true
  use_issues_button: true
